name: alsadhan
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  flutter_staggered_grid_view: ^0.3.0
  flutter_paginator: ^0.0.6
  shared_preferences: ^0.5.6+3
  badges: ^1.1.1
  gson: ^0.1.4
  intl: ^0.15.8
  toast: ^0.1.5
  progress_dialog: ^1.2.1
  flutter_typeahead: ^1.8.0
  google_fonts: ^0.3.10
  flutter_spinkit: "^4.1.2"
  gradient_text: ^1.0.2
  rate_my_app: ^0.6.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/right.png
    - images/non_food.jpg
    - images/others.jpg  
    - images/consumable_products.jpg
    - images/all_categories.jpg
    - images/others_new.jpg
   
    - images/non_food_new2.jpg
    - images/luggage.jpg
    - images/electronics.jpg
    - images/alsadanlogo.png
    - images/logo.png
    - images/sadhan_land.png
    - images/ic_thank_you.png
    - images/ic_about_us.png
    - images/ic_invite_friends.png
    - images/ic_notification.png
    - images/ic_payment.png
    - images/ic_logout.png
    - images/ic_settings.png
    - images/ic_qr_code.png
    - images/ic_support.png 
    - images/ic_search.png
    - images/ic_shopping_cart.png
    - images/super_market.jpg 
    - images/hot_deals.jpg 
    - images/hot_deals_n.jpg
    - images/fruits_banner.png
    - images/main_banner.jpg
    - images/splash_logo.jpg
    - images/Alsadhan_banner1.jpg
    - images/Spar-banner1.jpg
    - images/food-beeverages-A.jpg
    - images/non-food-A.jpg
    - images/fresh-food-A.jpg

    - images/spar-food-beverages.jpg
    - images/spar-fresh-food-ar.jpg
    - images/spar-non-food-ar.jpg
    - images/spar_appicon.jpg
  
  
# maincategory
    - images/SPAR_land.png
    - images/Spar-main-banner.png
    - images/spar-fruit-veg-baby-wipes.png
    - images/Category/baby_care.jpg
    - images/Category/fresh_food.jpg
    - images/Category/food_beverages.jpg
    - images/Category/frozen_food.jpg
    - images/Category/health_beauty.jpg
    - images/Category/healthy_liveing.jpg
    - images/Category/household.jpg
    - images/Category/super_market.jpg 
    - images/Category/super_market_offer.jpg 
    - images/Category/pets.jpg
    - images/Category/non-food.jpg

    - images/Category/sp-food-beverages-ar.jpg
    - images/Category/sp-fresh-food-ar.jpg
    - images/Category/sp-main-banner-ar.jpg
    - images/Category/sp-non-food-ar.jpg
    - images/Category/spar-all-categories-ar.jpg
    - images/Category/spar-non-food-ar.jpg

    # subcategory
    - images/SubCategory/baby_care.jpg
    - images/SubCategory/baby_food.jpg
    - images/SubCategory/bakery.jpg
    - images/SubCategory/breakfast.jpg
    - images/SubCategory/cosmetics.jpg
    - images/SubCategory/dairy.jpg
    - images/SubCategory/grocery.jpg   
    - images/SubCategory/fruits_vegs.jpg 
    - images/SubCategory/laundry_detergent.jpg
    - images/SubCategory/oil_ghees.jpg
    - images/SubCategory/pets_accessories.jpg
    - images/SubCategory/pets_food.jpg
    - images/SubCategory/skin_care.jpg
    - images/SubCategory/snacks.jpg
    - images/SubCategory/luggage.jpg
    - images/SubCategory/electronics.jpg

    - images/SubCategory/sp-bakery-ar.jpg
    - images/SubCategory/sp-breakfast-ar.jpg
    - images/SubCategory/sp-electronics-ar.jpg
    - images/SubCategory/sp-fruits-vegitables.jpg
    - images/SubCategory/sp-luggage-ar.jpg
    - images/SubCategory/sp-snacks-ar.jpg

    # - images/bakery.jpg
    # - images/fruits_vegs.jpg
    # - images/snacks.jpg
    # - images/oil_gees.jpg
    # - images/skin_care.jpg
    # - images/baby_care.jpg
    # - images/fresh_food.jpg     


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry       in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/helvetica/HelveticaNeue_Light.ttf
          weight: 200
        - asset: fonts/helvetica/HelveticaNeue_Regular.ttf
          weight: 400
        - asset: fonts/helvetica/HelveticaNeue_Medium.ttf
          weight: 500
        - asset: fonts/helvetica/HelveticaNeue-Bold.ttf
          weight: 700
        - asset: fonts/helvetica/HelveticaNeue_BlackCond.ttf
          weight: 900
  # 










